### ISSUE TITLE
Add instructions on linking packages

### ISSUE THREAD

**Issue by ghost** [dhis2/cli-packages#12]
From slack discussion:

Original question:

> I'm working on d2-ui for a bug in the maintenance app. Can anyone tell me how I'd yarn link d2-ui/packages/legend, so I can yarn-link it in my maintenance-app repo?

Instructions:

```
cd d2-ui/packages/legend/build
yarn link
cd maintenance-app
yarn link @dhis2/d2-ui-legend`
```

Make sure you build `packages/legend` first, or have a `watch` running of it.

**Comment by amcgee** [comment]
@ismay great to document this, but it should go in the [d2-ui](https://github.com/dhis2/d2-ui) repo!

**Comment by ghost** [comment]
Yeah you're right, thanks!
